baseURL: http://hankcsh.github.io/
languageCode: en-us
title: Hank CHEN
theme: hugo-theme-stack
DefaultContentLanguage: en

languages:
    en:
        languageName: English
        title: Hank CHEN
        weight: 1
    zh-tw:
        languageName: 中文
        title: 陳首翰
        weight: 2

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          params:
            icon: home
            newTab: false

    social:
        - identifier: GitHub
          name: GitHub
          url: https://github.com/HankCSH
          weight: 1
          params:
              icon: brand-github

        - identifier: ResearchGate
          name: ResearchGate
          url: https://www.researchgate.net/profile/Sou-Han-Chen
          weight: 2
          params:
              icon: researchgate
        
        - identifier: LinkedIn
          name: LinkedIn
          url: https://www.linkedin.com/in/hankchenhk/
          weight: 3
          params:
              icon: LinkedIn

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:  # e.g.: favicon placed in `static/favicon.ico` of your site folder, then set this field to `/favicon.ico` (`/` is necessary)

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji:
        subtitle: Research Assistant @ HKU
        avatar:
            enabled: true
            local: true
            src: img/coverphoto.jpeg