baseURL: http://hankcsh.github.io/
languageCode: en-us
title: Hank CHEN
theme: hugo-theme-stack
DefaultContentLanguage: en

languages:
    en:
        languageName: English
        title: Hank CHEN
        weight: 1
    zh-tw:
        languageName: 中文
        title: 陳首翰
        weight: 2

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: 1
          params:
            icon: home
            newTab: false
        - identifier: Resume
          name: Resume
          url: /cv
          weight: 2
          params:
            icon: archives
            newTab: false
        - identifier: Publication
          name: Publication
          url: /pb
          weight: 3
          params:
            icon: hash
            newTab: false

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/HankCSH
          params:
              icon: brand-github

        - identifier: researchgate
          name: ResearchGate
          url: https://www.researchgate.net/profile/Sou-Han-Chen
          params:
              icon: categories

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:  # e.g.: favicon placed in `static/favicon.ico` of your site folder, then set this field to `/favicon.ico` (`/` is necessary)

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji:
        subtitle:
        avatar:
            enabled: true
            local: true
            src: img/coverphoto.jpeg